In [1]:
from models.vae_model import VaeModel

VAE = VaeModel(
    model_path="GrafikXxxxxxxYyyyyyyyyyy/sdxl_Juggernaut",
    model_type="sdxl",
    device="mps",
)

VAE model has successfully loaded from 'GrafikXxxxxxxYyyyyyyyyyy/sdxl_Juggernaut' checkpoint!


In [2]:
from pipelines.vae_pipeline import VaePipeline, VaePipelineInput, VaePipelineOutput

pipeline = VaePipeline()

In [3]:
from diffusers.utils import load_image, make_image_grid

init_image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint.png")
mask_image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint_mask.png")

vae_input = VaePipelineInput(
    width=512,
    height=512,
    image=init_image,
    mask_image=mask_image,
)

In [4]:
output = pipeline(
    VAE,
    **vae_input,
)

In [5]:
image_latents, mask, masked_image_latents = output(1, 1, "mps")

In [6]:
image_latents

tensor([[[[-2.6782e-01,  7.4348e-03,  4.6509e-01,  ..., -6.0455e-02,
           -8.1299e-01, -1.2305e+00],
          [-7.3877e-01, -1.1318e+00,  6.4990e-01,  ..., -1.1719e+00,
            5.4883e-01, -7.5000e-01],
          [-1.0967e+00, -1.9324e-01,  6.4648e-01,  ..., -4.6533e-01,
            5.8075e-02, -1.5918e+00],
          ...,
          [-6.5039e-01,  1.7920e-01, -3.9136e-01,  ..., -4.2798e-01,
            5.6250e-01, -3.9941e-01],
          [-3.0298e-01, -3.1055e-01, -5.5371e-01,  ...,  5.9912e-01,
            7.9150e-01, -2.4304e-01],
          [-3.1543e-01, -4.0820e-01, -8.8379e-01,  ...,  4.3481e-01,
            8.3203e-01,  8.5547e-01]],

         [[ 1.1670e+00,  2.4551e-02,  7.1875e-01,  ...,  3.4302e-01,
           -3.2764e-01, -1.7041e-01],
          [ 6.3770e-01, -3.5181e-01, -3.2446e-01,  ..., -4.2033e-04,
            1.1318e+00,  3.9160e-01],
          [ 5.2783e-01,  1.1650e+00,  1.1591e-01,  ..., -8.1238e-02,
            1.2705e+00,  3.3539e-02],
          ...,
     

In [7]:
mask

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='mps:0',
       dtype=torch.float16)

In [8]:
masked_image_latents

tensor([[[[-0.2603,  0.0131,  0.4724,  ..., -0.0540, -0.8071, -1.2275],
          [-0.7349, -1.1299,  0.6577,  ..., -1.1709,  0.5630, -0.7427],
          [-1.0947, -0.1843,  0.6553,  ..., -0.4568,  0.0670, -1.5908],
          ...,
          [-0.6587,  0.1392, -0.3979,  ..., -0.4309,  0.5659, -0.4033],
          [-0.3032, -0.3154, -0.5547,  ...,  0.5986,  0.7979, -0.2467],
          [-0.3142, -0.4080, -0.8843,  ...,  0.4397,  0.8330,  0.8584]],

         [[ 1.1729,  0.0250,  0.7231,  ...,  0.3418, -0.3230, -0.1693],
          [ 0.6426, -0.3450, -0.3154,  ...,  0.0064,  1.1416,  0.4041],
          [ 0.5322,  1.1719,  0.1277,  ..., -0.0697,  1.2852,  0.0414],
          ...,
          [-1.0996,  0.1000, -0.1985,  ..., -0.5552,  0.4905, -0.7056],
          [-0.2578, -0.0790, -0.1433,  ..., -0.1356, -0.0915, -0.6992],
          [ 0.6396,  0.2195, -0.7510,  ..., -0.9502, -0.3584,  0.5337]],

         [[-0.3242, -1.0654, -1.9590,  ..., -1.0791,  0.7236, -1.0908],
          [-1.7588, -1.2285,  

In [9]:
VAE.decode(image_latents)

RuntimeError: MPS backend out of memory (MPS allocated: 8.85 GB, other allocations: 195.89 MB, max allowed: 9.07 GB). Tried to allocate 64.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).